Feature/add api endpoint
i-dot-ai/one-big-thing pull request #231
Opened 2023-09-14 12:08 UTC by 252afh

- Added property to model
- Added required permission restrictions to token generation and api endpoints
- Added API endpoint that just returns user id's
- Added required packages

2023-09-14 12:16 UTC, gecBurton commented on one_big_thing/learning/models.py
> +    is_api_user = models.BooleanField(default=False)
this will have to be null=True, blank=True for existing users?

2023-09-15 11:48 UTC, gecBurton commented on one_big_thing/api_serializers.py
> +        fields = [
```suggestion
        fields = "__all__"
```

2023-09-15 11:53 UTC, gecBurton requested changes
that was quick! But...
1. regenerate the migrations
2. test that the auth is working, see https://djangostars.com/blog/django-pytest-testing/
3. (if possible) convert the DS query to ORM annotate, im pretty sure this is possible,
4. write a test for that too

2023-09-15 11:53 UTC, gecBurton commented on one_big_thing/learning/api_views.py
> +def get_learning_breakdown_data(department_dict):
you can do (probably) all of this will `annotate`, it will be a lot faster.

2023-09-15 11:53 UTC, gecBurton commented on one_big_thing/learning/migrations/0017_user_is_api_user.py
> +from django.db import migrations, models
kill both migrations and regenerate them. this one will fail because of existing users not having `is_api_user` values yet

2023-09-18 07:35 UTC, gecBurton commented on one_big_thing/learning/api_views.py
> +    for user_count in user_counts:
you can use the same `annotate` `value` "group by" stunt as you used in `get_learning_breakdown_data` here too

2023-09-18 07:36 UTC, gecBurton commented on one_big_thing/learning/api_views.py
> +        **{
:+1:

2023-09-18 07:37 UTC, gecBurton commented on one_big_thing/learning/api_views.py
> +    groupings = models.User.objects.values("department", "grade", "profession").annotate(
add a brief doc string "this is a script used by 10DS to ingest data for reporting used adoption of OBT" or something lie that

2023-09-18 07:38 UTC, gecBurton commented on one_big_thing/settings.py
> +    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
I told TDA 5 mins and 1 day respectively. but given that i expect they will use it once a month i dont think it really matters!

2023-09-18 07:41 UTC, gecBurton commented on pytest_tests/test_api.py
> +    client = APIClient()
```suggestion
```

you dont need this line. `client` is an inbuilt fixture, you can just add it as a parameter to your test

2023-09-18 07:42 UTC, gecBurton commented on pytest_tests/test_api.py
> +def token_fixture():
i really like this one, and especially the way it cascades throughout your tests

2023-09-18 07:49 UTC, gecBurton requested changes
this is very nice

pls do:
* https://github.com/i-dot-ai/one-big-thing/pull/231/files#r1328339554 as this will hit the db hard
* disable this in production as we dont yet have approval for it... i am working on this today

some optional non blocking thoughts....
1. ideally we should test that your complex queries work. the 10DS one will be hard.... but the user stats should be easy as you can copy what i did in test_user_stats.py
2. some of your fixtures are v nice, and might be helpful elsewhere..... if this is the case you can move them into `conftest.py` where they will be accessible to any test

2023-09-18 12:04 UTC, 252afh commented on one_big_thing/settings.py
> +    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
I assume they want the dashboard to be pulling data from it?

2023-09-18 12:40 UTC, 252afh commented on pytest_tests/test_api.py
> +    client = APIClient()
APIClient is not a build-in fixture

2023-09-19 12:21 UTC, gecBurton approved these changes
LGTM

2023-09-19 12:21 UTC, merged