Bugfix/fix validation
i-dot-ai/one-big-thing pull request #246
Opened 2023-09-25 06:48 UTC by nmenezes0

Fix validation on the page where users are recording learning.

If users leave either the hours field blank or the minutes field blank (not both) - there should be no error, and we assume that it's zero.

If both the hours and the minutes are blank, then there should be an error.

2023-09-25 08:03 UTC, 252afh requested changes

2023-09-25 08:03 UTC, 252afh commented on one_big_thing/learning/schemas.py
>      validate_positive_integer(value, max=59, error_msg=minutes_error)
Not sure why, but entering a large minute causes the error to be returning twice
![image](https://github.com/i-dot-ai/one-big-thing/assets/30538514/9d7a5705-acd3-462a-b09a-510f877958bd)

2023-09-25 08:03 UTC, 252afh commented on one_big_thing/learning/schemas.py
>      validate_positive_integer(value, max=59, error_msg=minutes_error)
Same with hours 
![image](https://github.com/i-dot-ai/one-big-thing/assets/30538514/65a34dc3-4f38-4e6d-8d41-d8bd3026e251)

2023-09-25 08:03 UTC, 252afh commented on one_big_thing/learning/schemas.py
>      validate_positive_integer(value, max=59, error_msg=minutes_error)
Same with large numbers
![image](https://github.com/i-dot-ai/one-big-thing/assets/30538514/c0759104-b2db-406a-b7c7-70a7d0dcf7c2)

2023-09-26 14:39 UTC, nmenezes0 commented
Ready for you to break it again @252afh - think I've fixed the issues with duplicate messages.

2023-09-28 09:56 UTC, 252afh approved these changes

2023-09-28 09:56 UTC, merged