Feature/department as model
i-dot-ai/one-big-thing pull request #270
Opened 2023-10-17 15:48 UTC by gecBurton

2023-10-18 08:30 UTC, gecBurton commented on one_big_thing/learning/constants.py
> -DEPARTMENTS_USING_INTRANET_LINKS = {
i have moved this into a model and database migration

2023-10-18 08:34 UTC, gecBurton commented on one_big_thing/learning/models.py
> +    def choices(cls) -> list[tuple[Any, Any]]:
we could cache this?

2023-10-18 08:36 UTC, gecBurton commented on one_big_thing/learning/schemas.py
> +    def validate_department(self, value):
now that the departments aren't static we need to make this validation dynamic

2023-10-18 09:14 UTC, gecBurton commented on tests/test_totp_admin.py
> +        self.assertEqual(response.status_code, 302)
oops! this change inadvertently corrects an error

2023-10-18 09:14 UTC, gecBurton commented on one_big_thing/learning/models.py
> +    ATTORNEY_GENERALS_DEPARTMENTS = "ATTORNEY_GENERALS_DEPARTMENTS"
this list is from 10DS

2023-10-18 09:15 UTC, gecBurton commented on one_big_thing/learning/admin.py
> -admin_site = OTPAdmin(name="OTPAdmin")
we want to use the normal admin locally

2023-10-19 18:59 UTC, nmenezes0 commented
> ![image](https://user-images.githubusercontent.com/8233643/276187082-3babf32f-981f-4324-9995-3debffd7b421.png)

Looks like the "Other" depts are incorrectly given the parent dept as "Defra".

2023-10-19 19:06 UTC, nmenezes0 commented on one_big_thing/learning/models.py
> +    DEPARTMENT_FOR_BUSINESS_AND_TRADE_ = "DEPARTMENT_FOR_BUSINESS_AND_TRADE_"
Is there a reason for the underscore after the name? (Not that it particularly makes a diff.)

2023-10-19 20:11 UTC, nmenezes0 commented on departments.csv
> +"acas", "The Advisory, Conciliation and Arbitration Service (Acas)", "DEPARTMENT_FOR_ENVIRONMENT_FOOD_AND_RURAL_AFFAIRS", null
Is this right for Acas? https://www.gov.uk/government/organisations/acas
Also don't think it's right for "queen-elizabeth-ii-conference-centre", "Queen Elizabeth II Conference Centre (QEIICC)" (arms' length body of DLUCH)

Looks like something might have gone wrong when compiling the list and DEFRA keeps appearing as parent org.

2023-10-19 20:15 UTC, nmenezes0 commented
Haven't tested or reviewed in detail - but approach looks fine to me. Just a few possible data issues have snuck in there (see comments).

2023-10-20 05:46 UTC, gecBurton commented on one_big_thing/learning/models.py
> +    DEPARTMENT_FOR_BUSINESS_AND_TRADE_ = "DEPARTMENT_FOR_BUSINESS_AND_TRADE_"
no reason. this is a typo

2023-10-20 05:46 UTC, gecBurton commented on departments.csv
> +"acas", "The Advisory, Conciliation and Arbitration Service (Acas)", "DEPARTMENT_FOR_ENVIRONMENT_FOOD_AND_RURAL_AFFAIRS", null
good point!

2023-10-20 11:00 UTC, gecBurton commented on departments.csv
> +"acas", "The Advisory, Conciliation and Arbitration Service (Acas)", "DEPARTMENT_FOR_ENVIRONMENT_FOOD_AND_RURAL_AFFAIRS", null
[78df662](https://github.com/i-dot-ai/one-big-thing/pull/270/commits/78df662a8c115f5e78b91cd50b2a114673c8739e)

2023-10-24 10:49 UTC, nmenezes0 commented on pytest_tests/test_migrations.py
> +    migrator = Migrator(database="default")
This is fun, I've never tested a migration before.

2023-10-24 12:15 UTC, nmenezes0 commented on one_big_thing/learning/models.py
> +    old_department = models.CharField(max_length=254, blank=True, null=True)
Maybe in a separate PR once the changes have been deployed and we're happy?

2023-10-24 12:23 UTC, nmenezes0 commented on one_big_thing/learning/schemas.py
> +    def validate_department(self, value):
Need a decorator `@validates("department")` - https://marshmallow.readthedocs.io/en/stable/quickstart.html#field-validators-as-methods

2023-10-24 12:32 UTC, nmenezes0 commented on one_big_thing/learning/schemas.py
> +    def validate_department(self, value):
Test if you want to use it (I was writing one so I could test):
```
def test_my_details_schema():
    details_schema = schemas.MyDetailsSchema()
    invalid = {"department": "dodgy-dept", "grade": "GRADE7", "profession": "ANALYSIS"}
    valid = {"department": "cabinet-office", "grade": "GRADE7", "profession": "ANALYSIS"}
    validation_issues = details_schema.validate(invalid)
    assert "department" in validation_issues, validation_issues
    validation_issues = details_schema.validate(valid)
    assert not validation_issues, validation_issues
```

2023-10-24 12:40 UTC, nmenezes0 commented
In the "My details page" (http://localhost:8055/my-details/), the department is always displaying as Acas. Have checked in the DB and the correct department is save (the correct department having been saved previously, and that one wasn't Acas).

Not sure what's going on here - something in the view/template?

2023-10-24 13:31 UTC, nmenezes0 commented on one_big_thing/learning/migrations/departments.csv
> +"code", "display", "parent", "url"
Assume there's only a URL for streamlined departments? Is it worth changing the title of the column (here, or in the model) as there are also other departmental URLs flying around?

Not necessary change - just a thought.

2023-10-24 13:34 UTC, nmenezes0 requested changes
Only two things that need to be changed (there are comments in the PR):
1. The validation for departments
2. The issue where the my details form isn't being populated properly for the department

Otherwise looks good - other comments are minor, or questions for my understanding.

2023-10-25 09:22 UTC, gecBurton commented
> In the "My details page" (http://localhost:8055/my-details/), the department is always displaying as Acas. Have checked in the DB and the correct department is save (the correct department having been saved previously, and that one wasn't Acas).
> 
> Not sure what's going on here - something in the view/template?
> 
> ![image](https://user-images.githubusercontent.com/77671865/277662732-2e76d804-267b-4537-a986-0dcae07b33a3.png)

good spot! fixed here [658e9af](https://github.com/i-dot-ai/one-big-thing/pull/270/commits/658e9af8a1ca3aca2ca4b402ac74aa9144488add)

2023-10-25 10:21 UTC, nmenezes0 commented on one_big_thing/learning/schemas.py
> +    def validate_department(self, value):
@gecBurton - has this validation been fixed too?

2023-10-25 12:46 UTC, nmenezes0 approved these changes

2023-10-25 13:01 UTC, merged